swagger: '2.0'
info:
  version: 1.0.0
  title: BACK-END - user authetication API 
  description: em contrução 

host: localhost:3000
basePath: /

paths:
  /auth/register:
    post:
      summary: Create | register a new user 
      description: Create a user based on Data 
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          required: true
          schema:
            $ref: '#/definitions/UserInput'
      responses:
        '200':
          description: sucess create user

definitions:
  UserInput:
    type: object
    properties:
      username:
        type: string
      password:
        type: string
